---
title: "My Story"
---

[LinkedIn](https://www.linkedin.com/in/christopher-smith-9a0508a8/)
[Twitter](https://twitter.com/C_smizzle)

##Stumbling (quite literally) Into a Love Affair with Data

To say that I was in love with data from day one would be a lie. I was a junior in college with aspirations to become the next hot shot on Wall Street, a dream many students with a financial background share. After a long weekend spent doing what most college students do, I found myself sitting in the library on a Sunday racing to catch up on work I swore to myself I would have completed by now. For a research paper in one of my needlessly redundant liberal arts filler classes required by undergraduate university, I chose the topic of emerging trends in technology across the globe. A broad topic, but one I felt conquerable in the 2 week span of the assignment. Unbeknownst to me, this topic contained endless depth and extremely high barrier to entry along with a complexity I have never encountered before. 

##An Ode to Barrack Obama

Immediately I was infatuated. As I continued my research, now with a triggered sense of curiosity, I came across an interview given by then [President Barack Obama on Wired](https://www.wired.com/2016/10/president-obama-mit-joi-ito-interview/). The topic of this interview surrounded Artificial Intelligence's effects on the global workforce, implications on National Security, and the overall direction of the generally perceived fantasy field. Now, without being political, Barack Obama could talk about linear algebra an I will be locked in for the duration. The man has a way with words. But throughout Obama's interview, topics of data science, machine learning, and artificial intelligence became real to me for the first time. Along with these topics, the need for talented, curious, and motivated people in that field also became very clear to me. I actually (fully aware of the corniness of my actions) said "Sign me up!" out loud in the library.

##Here We Are

Fast forward three years and I am currently in the process of obtaining my Masters' in Applied Data Science from the iSchool at Syracuse University. I have interned at both financial institutions and logistics companies, employing a robust statistical and data science driven analytic framework that has yielded great results for both me personally as well as my peers. I believe that bridging the gap between technical skills and outstanding communication will take virtually any organization to  unforeseen success. I look to demonstrate my wide range of data skills through this website along with adding some increments of my personality along the way. Enjoy!